// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrGxI_8FhAx5p6vgMWbubuBHU9_GhuQ6U',
    appId: '1:70978137442:web:b129a38262c4035ea1d03b',
    messagingSenderId: '70978137442',
    projectId: 'business-app-ac182',
    authDomain: 'business-app-ac182.firebaseapp.com',
    storageBucket: 'business-app-ac182.appspot.com',
    measurementId: 'G-VB7JJWG2MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2OYT85bmo6n2eq4DaahIxulWf0whgMY',
    appId: '1:70978137442:android:e4a0254db9299587a1d03b',
    messagingSenderId: '70978137442',
    projectId: 'business-app-ac182',
    storageBucket: 'business-app-ac182.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQBO7j5wGfb5FNmC9Bq_2RJpdKAgKSet8',
    appId: '1:70978137442:ios:5c13b70d9fea8c1aa1d03b',
    messagingSenderId: '70978137442',
    projectId: 'business-app-ac182',
    storageBucket: 'business-app-ac182.appspot.com',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQBO7j5wGfb5FNmC9Bq_2RJpdKAgKSet8',
    appId: '1:70978137442:ios:5c13b70d9fea8c1aa1d03b',
    messagingSenderId: '70978137442',
    projectId: 'business-app-ac182',
    storageBucket: 'business-app-ac182.appspot.com',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrGxI_8FhAx5p6vgMWbubuBHU9_GhuQ6U',
    appId: '1:70978137442:web:ef9df8e8c733a016a1d03b',
    messagingSenderId: '70978137442',
    projectId: 'business-app-ac182',
    authDomain: 'business-app-ac182.firebaseapp.com',
    storageBucket: 'business-app-ac182.appspot.com',
    measurementId: 'G-E30BPCTRL4',
  );
}
